### ISSUE TITLE
(Pyinstaller, Warning when bundling rapidfuzz as dependency) discover_hook_directories: Failed to process hook entry point '...rapidfuzz.__pyinstaller:get_hook_dirs': AttributeError: module 'rapidfuzz.__pyinstaller' has no attribute 'get_hook_dirs'

### ISSUE THREAD

**Issue by lokjunneo** [maxbachmann/rapidfuzz#441]
Description:

Using PyInstaller, when bundling `rapidfuzz` as a dependency, the following warning message appears:

```sh
discover_hook_directories: Failed to process hook entry point 'EntryPoint(name='hook-dirs', value='rapidfuzz.__pyinstaller:get_hook_dirs', group='pyinstaller40')': AttributeError: module 'rapidfuzz.__pyinstaller' has no attribute 'get_hook_dirs'
```

This was tested with an independent project that imports only `rapidfuzz` as its dependency.

---

I tried including the following into `src\rapidfuzz\__pyinstaller\__init__.py` (following the example by [PyInstaller](https://github.com/pyinstaller/hooksample/blob/master/src/pyi_hooksample/__pyinstaller/__init__.py)), and the warning no longer appears:

```py
import os

def get_hook_dirs():
    return [os.path.dirname(__file__)]
```

I believe this is caused by the following [line in pyproject.toml](https://github.com/rapidfuzz/RapidFuzz/blob/7cf8baf979c9bcccb2d2fcfbf1919a0689be54e2/pyproject.toml#L40):

```toml
[project.entry-points.pyinstaller40]
hook-dirs = "rapidfuzz.__pyinstaller:get_hook_dirs"
tests = "rapidfuzz.__pyinstaller:get_PyInstaller_tests"
```

as `get_hook_dirs` is not defined anywhere in the `__init__.py`
